basic build core structure is complete excluding install which I am not intending to do now

diff --git a/usr/local/bin/halogen b/usr/local/bin/halogen
--- a/usr/local/bin/halogen
+++ b/usr/local/bin/halogen
@@ -24,6 +24,7 @@ SQLITE_LOCAL='sqlite3 $lib_path/sqlite.local'
 
 # lfs
 export LFS=/mnt/lfs
+export LFS_TGT=x86_64-lfs-linux-gnu
 
 # Unorthodox way to check package manager dependancies.
 hash sqlite3 2> /dev/null || { echo >&2 "sqlite3 is required to run halogen. Aborting."; exit 1; }
@@ -44,18 +45,16 @@ function _aux_remote_db_touch {
 # __build_get_sources package_id
 #
 function __build_get_sources {
-	# pre-hooks
-	# main-hooks
-	echo "__build_get_sources()";
-	
+	echo "__build_get_sources(package_id)";
 	_db_cached_results_pkg_pkg=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT pkg FROM pkgs WHERE id=${1}"`
 	_db_cached_results_pkg_ver=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT ver FROM pkgs WHERE id=${1}"`
 	_db_cached_results_pkg_rev=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT rev FROM pkgs WHERE id=${1}"`
 	_db_cached_results_pkg_furl=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT furl FROM pkgs WHERE id=${1}"`
 	_db_cached_results_pkg_hash=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT hash FROM pkgs WHERE id=${1}"`
-	
 	_file_path_checksum="${_db_cached_results_pkg_pkg}-${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev}.checksum"
 	
+	# pre-hooks
+	# main-hooks
 	echo "downloading ${_db_cached_results_pkg_pkg}-${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev} .."
 	wget -q -N ${_db_cached_results_pkg_furl}
 	
@@ -71,29 +70,54 @@ function __build_get_sources {
 	done;
 	echo "Checksum OK !!"
 	
+	filename=$(basename "$_db_cached_results_pkg_furl")
+	filename="${filename%.*}"
+	rm -Rf $filename
 	tar -xf $(basename "${_db_cached_results_pkg_furl}")
 	# post-hooks
 	return 0;
 }
 function __build_configure {
+	echo "__build_configure()";
+	_db_cached_results_pkg_pkg=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT pkg FROM pkgs WHERE id=${1}"`
+	_db_cached_results_pkg_ver=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT ver FROM pkgs WHERE id=${1}"`
+	_db_cached_results_pkg_rev=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT rev FROM pkgs WHERE id=${1}"`
+	_db_cached_results_pkg_cfg=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT cfg FROM pkgs WHERE id=${1}"`
+	_db_cached_results_pkg_furl=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT furl FROM pkgs WHERE id=${1}"`
+	_pkg_name="${_db_cached_results_pkg_pkg} (${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev})"
 	# pre-hooks
 	# main-hooks
+	echo "configuring $_pkg_name .."
+	filename=$(basename "$_db_cached_results_pkg_furl")
+	filename="${filename%.*.*}"
+	cd /tmp/halogen && cd $filename && mkdir build
+	cd build
+	CFLAGS="${CFLAGS}" CXXFLAGS="${CFLAGS}" ../configure $_db_cached_results_pkg_cfg
 	# post-hooks
 	return 0;
 }
 function __build_make {
+	echo "__build_make(package_id)";
 	# pre-hooks
 	# main-hooks
+	make ${MAKEOPTS}
 	# post-hooks
 	return 0;
 }
 function __build_check {
+	echo "__build_check(package_id)";
 	# pre-hooks
 	# main-hooks
-	# post-hooks
-	return 0;
+	make ${MAKEOPTS} check
+	if [ $? -eq 0 ]; then
+		# post-hooks
+		return 0
+	fi
+    echo "__build_check(${1}) failed!"
+    exit 1;
 }
 function __build_install {
+	echo "__build_install(package_id)";
 	# pre-hooks
 	# main-hooks
 	# post-hooks
@@ -105,6 +129,10 @@ function _build_package {
 	cd ${TMP_PATH}
 	
 	__build_get_sources ${1}
+	__build_configure ${1}
+	__build_make ${1}
+	__build_check ${1}
+	__build_install ${1}
 	
 	# echo "fetching $_package .."
 	# apt-src install $_package
