more sqlite templates

diff --git a/usr/local/bin/halogen b/usr/local/bin/halogen
--- a/usr/local/bin/halogen
+++ b/usr/local/bin/halogen
@@ -20,26 +20,21 @@ source /etc/halogen.conf
 # definations
 BUILD_FLAGS='CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}"'
 # definations; cached queries
-__db_cached_query_pkg_pkgs="\"SELECT id FROM packages WHERE 1 ORDER BY id ASC\""
-__db_cached_query_pkg_pkg="\"SELECT pkg FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_pkg_ver="\"SELECT ver FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_pkg_rev="\"SELECT rev FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_pkg_url="\"SELECT url FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_pkg_furl="\"SELECT furl FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_pkg_hash="\"SELECT hash FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_get_pre_hooks="\"SELECT __build_get_sources_pre_hooks FROM packages WHERE id=\"${pkg_id}\"\""
-__db_cached_query_get_post_hooks="\"SELECT __build_get_sources_post_hooks FROM packages WHERE id=\"${pkg_id}\"\""
-function __db_cached_results {
-	# Turbo & Nitro
-	echo "${FUNCNAME[0]}(${1} ${2})"
-	rv="sqlite3 ${1} \"${2}\""
-	if [ $? -eq 0 ]; then
-		echo "query failed!"
-		_aux_set_package_sanity -1
-	fi
-	echo "${FUNCNAME[0]}(${1} ${2}) returned '${rv}'"
-	return ${rv}
+function __db_cached_results_pkg {
+	rv=$(sqlite3 ${1} "${2/DEF_PACKAGE_ID/${pkg_id}}") && echo "${FUNCNAME[0]}('${1}', '${2}') rv='${rv}'"
+	if [ $? -ne 0 ]; then echo "query failed!" && _aux_set_package_sanity -1 && exit 1; else return ${rv}; fi
 }
+function __db_cached_results_pkg_pkgs { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT id FROM packages WHERE 1 ORDER BY id ASC") }
+function __db_cached_results_pkg_pkg { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT pkg FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_ver { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT ver FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_rev { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT rev FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_url { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT url FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_furl { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT furl FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_hash { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT hash FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_get_pre_hooks { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT __build_get_sources_pre_hooks FROM packages WHERE id=DEF_PACKAGE_ID") }
+function __db_cached_results_pkg_get_post_hooks { return $(__db_cached_results_pkg ${REMOTE_DB} "SELECT __build_get_sources_pre_hooks FROM packages WHERE id=DEF_PACKAGE_ID") }
+
+function __db_cached_results_is_installed {	if [[ $(echo $(__db_cached_results ${LOCAL_DB} "SELECT count(*), * FROM packages WHERE pkg='${1}' AND ver='${2}' AND rev='${3}'") | awk '{split($0,a,"|"); print a[1]}') != "0" ]]; then return 1; else return 0; fi }
 
 mkdir $TMP_PATH &> /dev/null
 cd $TMP_PATH
@@ -68,33 +63,13 @@ export -f _aux_set_package_sanity
 function __build_get_sources() {
 	echo "${FUNCNAME[0]}(${pkg_id})"
 	
-	echo __db_cached_results ${REMOTE_DB} "${__db_cached_query_pkg_pkg}"
-	
-	# compat
-	# _db_cached_results_pkg_pkg=$(${__db_cached_results_pkg_pkg})
-	# _db_cached_results_pkg_ver=$(${__db_cached_results_pkg_ver})
-	# _db_cached_results_pkg_rev=$(${__db_cached_results_pkg_rev})
-	# _db_cached_results_pkg_furl=$(${__db_cached_results_pkg_furl})
-	# _db_cached_results_pkg_hash=$(${__db_cached_results_pkg_hash})
-	# _db_cached_results_pkg_pre_hooks=$(${__db_cached_results_pkg_get_pre_hooks})
-	# _db_cached_results_pkg_post_hooks=$(${__db_cached_results_pkg_get_post_hooks})
-	
-	# echo $_db_cached_results_pkg_pkg
-	# echo $_db_cached_results_pkg_ver
-	# echo $_db_cached_results_pkg_rev
-	# echo $_db_cached_results_pkg_furl
-	# echo $_db_cached_results_pkg_hash
-	# echo $_db_cached_results_pkg_pre_hooks
-	# echo $_db_cached_results_pkg_post_hooks
-
-	# constants
-	_file_path_checksum="${_db_cached_results_pkg_pkg}-${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev}.checksum"
+	_file_path_checksum="$(__db_cached_results_pkg_pkg)-$(__db_cached_results_pkg_ver)r$(__db_cached_results_pkg_rev).checksum"
 	
 	cd /tmp/halogen
 	
 	$_db_cached_results_pkg_pre_hooks
-	echo "downloading ${_db_cached_results_pkg_pkg}-${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev} .."		# DOWNLOADING PACKAGE
-	wget -q -N ${_db_cached_results_pkg_furl}																			# --
+	echo "downloading $(__db_cached_results_pkg_pkg)-$(__db_cached_results_pkg_ver)build$(__db_cached_results_pkg_rev) .."		# DOWNLOADING PACKAGE
+	wget -q -N $(__db_cached_results_pkg_furl)																					# --
 	
 	rm -f $_file_path_checksum											# CHECKSUMMING PACKAGE
 	echo "$_db_cached_results_pkg_hash" >> $_file_path_checksum			# --
@@ -102,7 +77,7 @@ function __build_get_sources() {
 	i=0
 	while [[ $? != 0 && i < 3 ]]; do									# --
 		echo "Checksum INVALID !!"										# --
-		wget -q ${_db_cached_results_pkg_furl}							# --
+		wget -q $(__db_cached_results_pkg_furl)							# --
 		i=i+1															# --
 	done;																# --
 	if [ i >= 3 ]; then
@@ -123,7 +98,7 @@ function __build_add_structure() {
 	
 	$_db_cached_results_pkg__build_add_structure_pre_hooks
 	
-	_pkg_packagename=$(basename "$_db_cached_results_pkg_furl")
+	_pkg_packagename=$(basename "$(__db_cached_results_pkg_furl)")
 	_pkg_foldername="${_pkg_packagename%.*.*}"
 	
 	cd /tmp/halogen && rm -Rf ${_pkg_foldername} && tar -xf ${_pkg_packagename} && mkdir ${_pkg_foldername}/build && cd ${_pkg_foldername}/build
@@ -146,7 +121,7 @@ function __build_configure() {
 	_db_cached_results_pkg_furl=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT furl FROM pkgs WHERE id=${pkg_id}"`
 	_db_cached_results_pkg_pre_hooks=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT __build_configure_pre_hooks FROM pkgs WHERE id=${pkg_id}"`
 	_db_cached_results_pkg_post_hooks=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT __build_configure_post_hooks FROM pkgs WHERE id=${pkg_id}"`
-	_pkg_name="${_db_cached_results_pkg_pkg} (${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev})"
+	_pkg_name="$(__db_cached_results_pkg_pkg) ($(__db_cached_results_pkg_ver)r$(__db_cached_results_pkg_rev))"
 
 	$_db_cached_results_pkg_pre_hooks
 	# main-hooks
@@ -262,7 +237,7 @@ function _build_package {
 	_db_cached_results_pkg_pkg=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT pkg FROM pkgs WHERE id=${pkg_id}"`
 	_db_cached_results_pkg_ver=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT ver FROM pkgs WHERE id=${pkg_id}"`
 	_db_cached_results_pkg_rev=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT rev FROM pkgs WHERE id=${pkg_id}"`
-	_pkg_name="${_db_cached_results_pkg_pkg} (${_db_cached_results_pkg_ver}r${_db_cached_results_pkg_rev})"
+	_pkg_name="$(__db_cached_results_pkg_pkg) ($(__db_cached_results_pkg_ver)r$(__db_cached_results_pkg_rev))"
 
 	export usermode_build_succeeded=0
 	
@@ -440,8 +415,8 @@ function _bootstrap_lfs_user {
 	
 	_aux_remote_db_touch;
 
-	# query
-	pkgs=$(__db_cached_results ${REMOTE_DB} \"${__db_cached_query_pkg_pkgs}\")
+	# basic manipulative query
+	pkgs=$(__db_cached_results_pkg ${REMOTE_DB} "${__db_cached_query_pkg_pkgs}")
 	
 	for package_id in ${pkgs}; do
 		export pkg_id=${package_id}
@@ -451,26 +426,23 @@ function _bootstrap_lfs_user {
 			exit 0
 		fi
 		
-		_db_cached_results_pkg_pkg=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT pkg FROM pkgs WHERE id=${pkg_id}"`
-		_db_cached_results_pkg_ver=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT ver FROM pkgs WHERE id=${pkg_id}"`
-		_db_cached_results_pkg_rev=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT rev FROM pkgs WHERE id=${pkg_id}"`
-		_db_cached_results_pkg_cfg=`sqlite3 /var/lib/halogen/sqlite.remote "SELECT cfg FROM pkgs WHERE id=${pkg_id}"`
-		_db_cached_results_is_installed=`sqlite3 /var/lib/halogen/sqlite.local "SELECT count(*), * FROM pkgs WHERE pkg='${_db_cached_results_pkg_pkg}' AND ver='${_db_cached_results_pkg_ver}' AND rev='${_db_cached_results_pkg_rev}'"`
+		_db_cached_results_pkg_pkg=$(__db_cached_results_pkg ${REMOTE_DB} "${__db_cached_query_pkg_pkg}")
+		_db_cached_results_pkg_ver=$(__db_cached_results_pkg ${REMOTE_DB} "${__db_cached_query_pkg_ver}")
+		_db_cached_results_pkg_rev=$(__db_cached_results_pkg ${REMOTE_DB} "${__db_cached_query_pkg_rev}")
+		_db_cached_results_pkg_cfg=$(__db_cached_results_pkg ${REMOTE_DB} "${__db_cached_query_pkg_cfg}")
+		_db_cached_results_is_installed=$(__db_cached_results_pkg ${LOCAL_DB} "${__db_cached_query_pkg_is_installed}")
 
-		_pkg_name="${_db_cached_results_pkg_pkg} ($_db_cached_results_pkg_ver-r${_db_cached_results_pkg_rev})"
-		echo "${FUNCNAME[0]}(null) working on ${_pkg_name} id=${pkg_id}.."
+		_pkg_name="$(__db_cached_results_pkg_pkg) ($_db_cached_results_pkg_ver-r$(__db_cached_results_pkg_rev))"
+		echo "${FUNCNAME[0]}(${1}) working on ${_pkg_name} id=${pkg_id}.."
 		
-		if [[ $(echo ${_db_cached_results_is_installed} | awk '{split($0,a,"|"); print a[1]}') != "0" ]]; then
-			echo "${_pkg_name} is already installed. rolling on.."
-			continue;
-		fi
+		if [[ $(__db_cached_results_is_installed $(__db_cached_results_pkg_pkg) $(__db_cached_results_pkg_ver) $(__db_cached_results_pkg_rev)) == 1 ]]; then echo "package is already installed, rolling on.." && continue; fi
 		
 		su lfs -c '_build_package'		# download, hash, fold, configure, build and check as normal user
 		if [ ${usermode_build_succeeded} -ne 1 ]; then echo "For some reason _build_package was succesful but usermode_build_succeeded=${usermode_build_succeeded}" && exit -1; fi
 		_build_package_root				# install and sanitize as root because I'm lazy..
 		echo "_build_package_root rv = $?"
 		if [ $? -ne 0 ]; then echo "NOT EQUAL 0!! HALT!!" && exit -1; fi
-		sqlite3 /var/lib/halogen/sqlite.local "INSERT INTO pkgs (pkg, ver, rev) VALUES ('${_db_cached_results_pkg_pkg}', '${_db_cached_results_pkg_ver}', '${_db_cached_results_pkg_rev}')"	# mark installed
+		sqlite3 /var/lib/halogen/sqlite.local "INSERT INTO pkgs (pkg, ver, rev) VALUES ('$(__db_cached_results_pkg_pkg)', '$(__db_cached_results_pkg_ver)', '$(__db_cached_results_pkg_rev)')"	# mark installed
 	done
 	return 0;
 }
@@ -489,52 +461,6 @@ case ${1} in
 #	echo "Updating package databases .."
 #	wget -q -O  /var/lib/halogen/sqlite.remote https://github.com/nafac/halogen/raw/master/var/lib/halogen/sqlite.remote
     exit 0;;
-#  bootstrap-update-host-toolchain)
-#	_aux_root_check ${1}
-#	echo "downloading binutils and dependancies.."
-#	cd /tmp/halogen
-#	wget -q -N https://ftp.gnu.org/gnu/binutils/binutils-2.26.1.tar.gz
-#	rm -Rf binutils-2.26.1
-#	tar -xf binutils-2.26.1.tar.gz
-#	mkdir binutils-2.26.1/build
-#	cd binutils-2.26.1/build
-#	echo "configuring binutils.."
-#	../configure --prefix=/usr --enable-shared --disable-werror
-#	if [ $? -eq 0 ]; then
-#		__build_package_simple
-#	else
-#		echo "Failed to configure!"
-#		exit 1
-#	fi
-#	echo "downloading glibc and dependancies.."
-#	cd /tmp/halogen
-#	wget -q -N https://ftp.gnu.org/gnu/glibc/glibc-2.24.tar.gz
-#	rm -Rf glibc-2.24
-#	tar -xf glibc-2.24.tar.gz
-#	mkdir glibc-2.24/build
-#	cd glibc-2.24/build
-#	echo "configuring glibc.."
-#	../configure --prefix=/usr --enable-kernel=4.4.25 --enable-obsolete-rpc
-#	if [ $? -eq 0 ]; then
-#		__build_package_simple
-#	else
-#		echo "Failed to configure!"
-#		exit 1
-#	fi
-
-#	echo "downloading gcc and dependancies.."
-#	cd /tmp/halogen
-#	wget -q -N https://ftp.gnu.org/pub/gnu/gcc/gcc-6.2.0/gcc-6.2.0.tar.gz
-#	_lfs_fetch_gcc_dependancies
-#	echo "oonfiguring gcc.."
-#	../configure -v --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-multilib --disable-bootstrap
-#	if [ $? -eq 0 ]; then
-#		__build_package_simple
-#	else
-#		echo "Failed to configure!"
-#		exit 1
-#	fi
-#	exit ;;
   bootstrap-lfs) 
 	_aux_root_check ${1}
 	_lfs_check_bootstrap_environment;
@@ -545,129 +471,6 @@ case ${1} in
 	_aux_root_check ${1}
 	_bootstrap_lfs_user;
 	exit ;;
-  build-base)
-    # query="SELECT * FROM packages_base WHERE 1"
-    # commit=`sqlite3 $lib_path/halogen.db "$query";
-    
-    # echo $commit
-    
-    # for row in $commit; do
-      # if [ -z "$row" ]; then
-        # echo "Halogen is (propably) complete!"
-        # exit 0
-      # fi
-      
-      # export pkg_name=`echo $row | awk '{split($0,a,"|"); print a[2]}'`
-      # export pkg_status=`echo $row | awk '{split($0,a,"|"); print a[3]}'`
-      
-      # source $lib_path/pkg/$pkg_name
-      
-      # echo $pkg_name
-      # echo $pkg_status
-      
-      # if [ "$pkg_status" == installed ]; then
-        # echo "Package $pkg_name is already installed, skipping." 
-        # continue
-      # fi
-     
-      # rm -Rf "${pkg_name}"
-      # rm -Rf "${pkg_name}-build"
-      
-      # echo "Downloading package $pkg_name ..."
-      # wget -nc -q -O $pkg_name $furl
-      
-      # echo "Extracting package $pkg_name ..."
-      # halogenzip ${pkg_name}
-      # mkdir "${pkg_name}-build"
-      # cd "${pkg_name}-build"
-      
-      # continue
-      
-      # echo "Patching ..."
-      # # pre hook
-      
-      # echo "Configuring archives of $pkg_name ..."
-      # echo $Conf
-      # ../$pkg_name/configure $Conf CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
-      
-      # echo "Building package of $pkg_name ..."
-      # echo "CFLAGS=$CFLAGS CXXFLAGS=$CXXFLAGS"
-      # make CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
-      
-      # if [ "$_make_check" -eq "1" ]; then
-	# return 1
-      # fi
-      
-      # $Id=$Id+1
-      # if [ $? -eq 0 ] ; then
-        # echo "Installing package $pkg_name ..."
-        # sudo make install
-        # if [ $? -eq 0 ] ; then
-          # sqlite3 $lib_path/remote.db "UPDATE base_packages SET status = 'Installed' WHERE id = $Id";
-        # else
-          # echo "$pkg_name - make install failed!"
-          # exit 1
-        # fi
-      # else
-        # echo "$pkg_name - make check failed!"
-        # exit 1
-      # fi
-      
-      # cd /tmp/halogen
-    # done
-    # exit 0;;
-  # optimize-debian)
-    # query="SELECT packages FROM packages_base_debian WHERE 1"
-    # commit=`sqlite3 $lib_path/halogen.db "$query"`;
-    
-    # IFS=$'\n'
-    # _lines=($commit)
-    
-    # for row in ${_lines[@]}; do 
-      # query="SELECT opt FROM packages_base_debian WHERE packages='$row'"
-      # export _opti=`sqlite3 $lib_path/halogen.db "$query"`;
-      
-      # IFS=$' '
-      # _packages=($row)
-
-      # for _package in ${_packages[@]}; do
-        # cd $tmp_path
-        
-        # _query="SELECT EXISTS(SELECT 1 FROM packages_installed WHERE package = '$_package' LIMIT 1);"
-        # _installed=`sqlite3 $lib_path/halogen.db "$_query"`;
-        
-        # echo "package = $_package - installed = $_installed - optimize = $_opti"
-        
-        # if [ "$_installed" -eq "1" ]; then
-          # echo "$_package is already installed."
-          # continue
-        # fi
-        
-        # echo "fetching $_package .."
-        # apt-src install $_package
-        
-        # unset $IFS
-        # cd ${tmp_path}/${_package}*
-        
-        # if _make_build $_opti; then
-          # echo
-        # else
-          # continue
-        # fi
-        # if _make_check; then
-          # echo
-        # else
-          # continue
-        # fi
-        # if _make_install; then
-          # sqlite3 $lib_path/halogen.db "INSERT INTO packages_installed (package) VALUES ('$_package')";
-        # else
-          # continue
-        # fi
-        # continue
-      # done
-    # done
-    exit ;;
   resume)
 	exit ;;
   *)
diff --git a/usr/local/bin/halogen-old b/usr/local/bin/halogen-old
--- a/usr/local/bin/halogen-old
+++ b/usr/local/bin/halogen-old
@@ -179,3 +179,174 @@ pkg_pre autogen-5.18.4
     CXXFLAGS="$OPTIMIZE_1"
 make CFLAGS="$OPTIMIZE_1" CXXFLAGS="$OPTIMIZE_1"
 pkg_post autogen-5.18.4
+
+# halogen alpha2
+#  bootstrap-update-host-toolchain)
+#	_aux_root_check ${1}
+#	echo "downloading binutils and dependancies.."
+#	cd /tmp/halogen
+#	wget -q -N https://ftp.gnu.org/gnu/binutils/binutils-2.26.1.tar.gz
+#	rm -Rf binutils-2.26.1
+#	tar -xf binutils-2.26.1.tar.gz
+#	mkdir binutils-2.26.1/build
+#	cd binutils-2.26.1/build
+#	echo "configuring binutils.."
+#	../configure --prefix=/usr --enable-shared --disable-werror
+#	if [ $? -eq 0 ]; then
+#		__build_package_simple
+#	else
+#		echo "Failed to configure!"
+#		exit 1
+#	fi
+#	echo "downloading glibc and dependancies.."
+#	cd /tmp/halogen
+#	wget -q -N https://ftp.gnu.org/gnu/glibc/glibc-2.24.tar.gz
+#	rm -Rf glibc-2.24
+#	tar -xf glibc-2.24.tar.gz
+#	mkdir glibc-2.24/build
+#	cd glibc-2.24/build
+#	echo "configuring glibc.."
+#	../configure --prefix=/usr --enable-kernel=4.4.25 --enable-obsolete-rpc
+#	if [ $? -eq 0 ]; then
+#		__build_package_simple
+#	else
+#		echo "Failed to configure!"
+#		exit 1
+#	fi
+
+#	echo "downloading gcc and dependancies.."
+#	cd /tmp/halogen
+#	wget -q -N https://ftp.gnu.org/pub/gnu/gcc/gcc-6.2.0/gcc-6.2.0.tar.gz
+#	_lfs_fetch_gcc_dependancies
+#	echo "oonfiguring gcc.."
+#	../configure -v --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-multilib --disable-bootstrap
+#	if [ $? -eq 0 ]; then
+#		__build_package_simple
+#	else
+#		echo "Failed to configure!"
+#		exit 1
+#	fi
+#	exit ;;
+ # build-base)
+    # query="SELECT * FROM packages_base WHERE 1"
+    # commit=`sqlite3 $lib_path/halogen.db "$query";
+    
+    # echo $commit
+    
+    # for row in $commit; do
+      # if [ -z "$row" ]; then
+        # echo "Halogen is (propably) complete!"
+        # exit 0
+      # fi
+      
+      # export pkg_name=`echo $row | awk '{split($0,a,"|"); print a[2]}'`
+      # export pkg_status=`echo $row | awk '{split($0,a,"|"); print a[3]}'`
+      
+      # source $lib_path/pkg/$pkg_name
+      
+      # echo $pkg_name
+      # echo $pkg_status
+      
+      # if [ "$pkg_status" == installed ]; then
+        # echo "Package $pkg_name is already installed, skipping." 
+        # continue
+      # fi
+     
+      # rm -Rf "${pkg_name}"
+      # rm -Rf "${pkg_name}-build"
+      
+      # echo "Downloading package $pkg_name ..."
+      # wget -nc -q -O $pkg_name $furl
+      
+      # echo "Extracting package $pkg_name ..."
+      # halogenzip ${pkg_name}
+      # mkdir "${pkg_name}-build"
+      # cd "${pkg_name}-build"
+      
+      # continue
+      
+      # echo "Patching ..."
+      # # pre hook
+      
+      # echo "Configuring archives of $pkg_name ..."
+      # echo $Conf
+      # ../$pkg_name/configure $Conf CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
+      
+      # echo "Building package of $pkg_name ..."
+      # echo "CFLAGS=$CFLAGS CXXFLAGS=$CXXFLAGS"
+      # make CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
+      
+      # if [ "$_make_check" -eq "1" ]; then
+	# return 1
+      # fi
+      
+      # $Id=$Id+1
+      # if [ $? -eq 0 ] ; then
+        # echo "Installing package $pkg_name ..."
+        # sudo make install
+        # if [ $? -eq 0 ] ; then
+          # sqlite3 $lib_path/remote.db "UPDATE base_packages SET status = 'Installed' WHERE id = $Id";
+        # else
+          # echo "$pkg_name - make install failed!"
+          # exit 1
+        # fi
+      # else
+        # echo "$pkg_name - make check failed!"
+        # exit 1
+      # fi
+      
+      # cd /tmp/halogen
+    # done
+    # exit 0;;
+  # optimize-debian)
+    # query="SELECT packages FROM packages_base_debian WHERE 1"
+    # commit=`sqlite3 $lib_path/halogen.db "$query"`;
+    
+    # IFS=$'\n'
+    # _lines=($commit)
+    
+    # for row in ${_lines[@]}; do 
+      # query="SELECT opt FROM packages_base_debian WHERE packages='$row'"
+      # export _opti=`sqlite3 $lib_path/halogen.db "$query"`;
+      
+      # IFS=$' '
+      # _packages=($row)
+
+      # for _package in ${_packages[@]}; do
+        # cd $tmp_path
+        
+        # _query="SELECT EXISTS(SELECT 1 FROM packages_installed WHERE package = '$_package' LIMIT 1);"
+        # _installed=`sqlite3 $lib_path/halogen.db "$_query"`;
+        
+        # echo "package = $_package - installed = $_installed - optimize = $_opti"
+        
+        # if [ "$_installed" -eq "1" ]; then
+          # echo "$_package is already installed."
+          # continue
+        # fi
+        
+        # echo "fetching $_package .."
+        # apt-src install $_package
+        
+        # unset $IFS
+        # cd ${tmp_path}/${_package}*
+        
+        # if _make_build $_opti; then
+          # echo
+        # else
+          # continue
+        # fi
+        # if _make_check; then
+          # echo
+        # else
+          # continue
+        # fi
+        # if _make_install; then
+          # sqlite3 $lib_path/halogen.db "INSERT INTO packages_installed (package) VALUES ('$_package')";
+        # else
+          # continue
+        # fi
+        # continue
+      # done
+    # done
+    # exit ;;
