LFS bootstrap

diff --git a/usr/local/bin/halogen b/usr/local/bin/halogen
--- a/usr/local/bin/halogen
+++ b/usr/local/bin/halogen
@@ -22,6 +22,9 @@ BUILD_FLAGS='CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}"'
 SQLITE_REMOTE='sqlite3 $lib_path/sqlite.remote'
 SQLITE_LOCAL='sqlite3 $lib_path/sqlite.local'
 
+# lfs
+export LFS=/mnt/lfs
+
 # Unorthodox way to check package manager dependancies.
 hash sqlite3 2> /dev/null || { echo >&2 "sqlite3 is required to run halogen. Aborting."; exit 1; }
 hash wget 2> /dev/null || { echo >&2 "wget is required to run halogen. Aborting."; exit 1; }
@@ -82,11 +85,101 @@ function _make_install {
 }
 # post
 
+# Linux From Scratch
+function _lfs_check_bootstrap_environment {
+	# toolchain check
+	export LC_ALL=C
+	bash --version | head -n1 | cut -d" " -f2-4
+	MYSH=$(readlink -f /bin/sh)
+	echo "/bin/sh -> $MYSH"
+	echo $MYSH | grep -q bash || echo "ERROR: /bin/sh does not point to bash"
+	unset MYSH
+
+	echo -n "Binutils: "; ld --version | head -n1 | cut -d" " -f3-
+	bison --version | head -n1
+
+	if [ -h /usr/bin/yacc ]; then
+	  echo "/usr/bin/yacc -> `readlink -f /usr/bin/yacc`";
+	elif [ -x /usr/bin/yacc ]; then
+	  echo yacc is `/usr/bin/yacc --version | head -n1`
+	else
+	  echo "yacc not found" 
+	fi
+
+	bzip2 --version 2>&1 < /dev/null | head -n1 | cut -d" " -f1,6-
+	echo -n "Coreutils: "; chown --version | head -n1 | cut -d")" -f2
+	diff --version | head -n1
+	find --version | head -n1
+	gawk --version | head -n1
+
+	if [ -h /usr/bin/awk ]; then
+	  echo "/usr/bin/awk -> `readlink -f /usr/bin/awk`";
+	elif [ -x /usr/bin/awk ]; then
+	  echo awk is `/usr/bin/awk --version | head -n1`
+	else 
+	  echo "awk not found" 
+	fi
+
+	gcc --version | head -n1
+	g++ --version | head -n1
+	ldd --version | head -n1 | cut -d" " -f2-  # glibc version
+	grep --version | head -n1
+	gzip --version | head -n1
+	cat /proc/version
+	m4 --version | head -n1
+	make --version | head -n1
+	patch --version | head -n1
+	echo Perl `perl -V:version`
+	sed --version | head -n1
+	tar --version | head -n1
+	makeinfo --version | head -n1
+	xz --version | head -n1
+
+	echo 'int main(){}' > dummy.c && g++ -o dummy dummy.c
+	if [ -x dummy ]
+	  then echo "g++ compilation OK";
+	  else echo "g++ compilation failed"; fi
+	rm -f dummy.c dummy
+	
+	# lib check
+	for lib in lib{gmp,mpfr,mpc}.la; do
+	echo $lib: $(if find /usr/lib* -name $lib|
+		grep -q $lib;then :;else echo not;fi) found
+	done
+	unset lib
+	
+	while true; do
+    read -p "** warning: are you sure your bootstrap environment is ready? **" yn
+    case $yn in
+        [Yy]* ) break;;
+        [Nn]* ) exit;;
+        * ) echo "please answer yes or no.";;
+    esac
+	done
+}
+function _lfs_prepare_disks {
+	mkdir -pv $LFS
+	mount -v -t ext4 $BOOTSTRAP_ROOT $LFS
+	/sbin/swapon -v $BOOTSTRAP_SWAP
+	mkdir -v $LFS/sources
+	chmod -v a+wt $LFS/sources
+	mkdir -v $LFS/tools
+	ln -sv $LFS/tools /
+	groupadd lfs
+	useradd -s /bin/bash -g lfs -m -k /dev/null lfs
+	passwd lfs
+	chown -v lfs $LFS/tools
+	chown -v lfs $LFS/sources
+	su - lfs
+}
+
 case $1 in
   update)
 	wget https://github.com/nafac/halogen/raw/master/var/lib/halogen/sqlite.remote /var/lib/halogen/sqlite.remote
     exit ;;
   bootstrap)
+	_lfs_check_bootstrap_environment;
+	_lfs_prepare_disks;
 	exit ;;
 
   # build-base)
